title: جهڙي سوچ
# author:
  # name: Aneel Kumar
  # email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  A public outlet for my personal expression جهڙي سوچ.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima
